baseURL: https://rsprojeto.github.io/blog-Renato-Silva/
languageCode: en
DefaultContentLanguage: en
title: Blog Data Sciences - Renato Silva
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
publishDir: docs/
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Renato Silva
  customCss: []
  customJs: []
  description: Call me Renato Silva
  doNotLoadAnimations: no
  favicon: favicons/favicon.icon
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/profile.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://de.linkedin.com/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/rsprojeto?tab=repositories
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:rsprojeto3d@gmail.com
  title: Renato Silva
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
